datasets:
  human_eval_v1:
    hf_name: "openai/openai_humaneval"
    hf_split: "test"
    sample_count: 164
    sample_seed: 1234
    output_dir: "/mnt/datasets-big/evals/human_eval_v1"
    dataset_type: human_eval

  mbpp_v1:
    hf_name: "google-research-datasets/mbpp"
    hf_split: "test"
    sample_count: 500
    sample_seed: 1234
    output_dir: "/mnt/datasets-big/evals/mbpp_v1"
    dataset_type: mbpp
